name: Build MarkForge

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---------------- LINUX / MAC ----------------
      - name: Install dependencies (Linux/macOS)
        if: matrix.os != 'windows-latest'
        run: |
          if [ "$RUNNER_OS" = "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y g++ sqlite3 libsqlite3-dev
          fi

          if [ "$RUNNER_OS" = "macOS" ]; then
            brew install sqlite

            SQLITE_PREFIX=$(brew --prefix sqlite)

            echo "SQLite prefix: $SQLITE_PREFIX"
            echo "SQLITE_PREFIX=$SQLITE_PREFIX" >> $GITHUB_ENV
          fi

      # ---------------- BUILD ----------------
      - name: Build project (Linux/macOS)
        if: matrix.os != 'windows-latest'
        run: |
          mkdir -p build

          FILES=$(find src -name "*.cpp")

          if [ "$RUNNER_OS" = "macOS" ]; then
            g++ -std=c++17 \
              -I${SQLITE_PREFIX}/include \
              -L${SQLITE_PREFIX}/lib \
              $FILES \
              -o build/markforge \
              -lsqlite3
          else
            g++ -std=c++17 \
              $FILES \
              -o build/markforge \
              -lsqlite3
          fi

      - name: Build project (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          mkdir build

          choco install mingw sqlite -y

          $FILES = Get-ChildItem -Recurse -Filter *.cpp | ForEach-Object FullName

          g++ -std=c++17 $FILES `
            -o build/markforge.exe `
            -lsqlite3

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: markforge-${{ matrix.os }}
          path: build/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/*